<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <PackageIcon>Transmission.png</PackageIcon>
        <Version>4.1.7</Version>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageId>Transmission.API.RPC.NET</PackageId>
        <Title>Transmission API RPC for .NET 10</Title>
        <Authors>Beatlegger, Lobanov</Authors>
        <Description>Client for Transmission API</Description>
        <Copyright>Copyright 2026</Copyright>
        <PackageTags>Transmission RPC NET10</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/LobanovAnton/Transmission.API.RPC.NET</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReleaseNotes>
4.1.7
• Update Readme.md 
• This version only contains an updated readme.md file, and it contains a link to a project that shows how to use it. Please download it and use it absolutely free.

4.1.6
• Fix sync method deadlock caused by SynchronizationContext in UI applications and mark them [Obsolete] 
If you want to call an asynchronous method synchronously, here is the recommended example: 
Statistic stat = GetSessionStatisticAsync().GetAwaiter().GetResult();

4.1.5
• Added CancellationToken parameter to Async methods.
If you don't need cancellation dont pass it or pass CancellationToken.None)

4.1.4
• Fix bug in function TorrentStartAsync (was start all torrents instead of by id)
• Update Microsoft.Extensions.Http to 10.0.3
• Update usage example in Readme.md

4.1.3
• Improving performance serializing request using the generated partial code of the JsonSerializerContext class
• Added required modifier for some fields, nullable value types has been removed
• Update usage example in Readme.md

4.1.2
• FreeSpace function now returns a FreeSpace class according to the original specification
• PortTest function now return a PortTest class according to the ooriginal specification
• Improving performance when deserializing objects using the generated partial code of the JsonSerializerContext class

4.1.1
• Fix type mismatch of field SequentialDownload in SessionInfo

4.1.0 
• The version corresponds to the minimum supported server 
• Support JSON-RPC 2.0
• Added GroupSet, GroupGet methods. 
• Added TorrentReannonce methods
• Added TorrentFields - Avalabilty, BytesCompleted, Group, SequentialDownload, SequentialDownloadFromPiece, BeginPiece, EndPiece
• Added SessionFields - BlocklistSize, ScriptTorrentAddedEnabled, ScriptTorrentAddedFilename, 
  ScriptTorrentDoneSeedingEnabled, ScriptTorrentDoneSeedingFilename, SequentialDownload, RpcVersionSemVer
• Added TransmissionTorrentPeers - IsIncoming, PeerId
• Added TransmissionTorrentPeersFrom - FromCache
• Added TransmissionTorrentTrackerStats - DownloaderCount, SiteName
            
2.2.2
• Use IHttpClientFactory instead of create new HttpClient for every request
• Added string[] fields as parameter to function GetSessionInformation
• Added static class SessionFields

2.2.0
• Porting the project to .Net 10.
• Using System.Text.Json instead of Newtonsoft Json.NET.
• Support for server version 4.1.0
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <None Include="Transmission.png" Pack="true" PackagePath="" />
        <None Include="README.md" Pack="true" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
    </ItemGroup>

</Project>
